### ISSUE TITLE
Feature request: add `hlGroup` filter parameter

### ISSUE THREAD

**Issue by matsui54** [tani/ddc-fuzzy#1]
Default highlight group of matched characters is `SpellBad`.
It would be convenient that we can change it like this.

```vim
call ddc#custom#patch_global('filterParams', {
    \ 'converter_fuzzy': {'hlGroup': 'Title'},
    \ })
```

**Comment by tani** [comment]
Sounds good. I'll do it. Thanks!

**Comment by tani** [comment]
Done. Thanks for giving nice suggestion

**Comment by matsui54** [comment]
Thank you!
