### ISSUE TITLE
Case-insensitive search 

### ISSUE THREAD

**Issue by marcinrogacki** [tani/ddc-fuzzy#2]
Is there an option to search ignoring upper words? E.g.: 
Type: creaus 
Result: createUser

**Comment by Shougo** [comment]
Please set `ddc-source-option-ignoreCase`.
`ddc-fuzzy` support it.

**Comment by marcinrogacki** [comment]
Working. Thanks for quick response. I am leaving snipped for other people.
 
```
call ddc#custom#patch_global('sourceOptions', {
\   '_': {
\     'matchers': ['matcher_fuzzy'],
\     'sorters': ['sorter_fuzzy'],
\     'converters': ['converter_fuzzy'],
\     'ignoreCase': 'true'
\   }
\ })
```
