### ISSUE TITLE
how to pop ddc for all members of a structure?

### ISSUE THREAD

**Issue by bon-ami** [tani/ddc-fuzzy#20]
In your demo clips, I saw actions like inputing "struct_name." and all members of it shows in a list.
I think ddc needs two letters to show anything. If I have a variable abc, containing a member def, I have to type "ab" for abc to show and have to type "abc.de" before def to show.
I'm using ale and statiolake/ddc-ale. Thanks.

**Comment by Shougo** [comment]
It is not `ddc-fuzzy` issue.

You  need to configure `forceCompletionPattern` like this.

```typescript
        lsp: {
          mark: "lsp",
          forceCompletionPattern: "\\.\\w*|::\\w*|->\\w*",
          dup: "force",
        },
```

**Comment by bon-ami** [comment]
https://github.com/Shougo/ddc.vim/issues/38
